### ISSUE TITLE
Expand borschik includes in client JS

### ISSUE THREAD

**Issue by tadatuta** [bem-site/bem-lib-site-data#11]
Now https://github.com/bem-site/bem-lib-site-data/blob/master/.enb/techs.js#L11 is used in
https://github.com/bem-site/bem-lib-site-data/blob/master/.enb/bundle-node-configurator.js which results in list of not expanded includes.

**Comment by iniel** [comment]
I think https://github.com/bem-site/bem-lib-site-data/pull/5/files fixes this problem.

**Comment by tadatuta** [comment]
@iniel that's true but I still not sure if we can get rid of `borschik` (e.g. some libraries use `borschik:include` in their blocks).
